"""initial schema

Revision ID: b6be6e36ae3d
Revises: 
Create Date: 2026-09-24 23:58:51.107181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6be6e36ae3d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allowed_countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('allowed_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('change_type', sa.String(length=16), nullable=False),
    sa.Column('field_name', sa.String(length=64), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_table('source_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.String(length=16), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_documents_file_hash'), 'source_documents', ['file_hash'], unique=False)
    op.create_table('import_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_document_id', sa.Integer(), nullable=True),
    sa.Column('is_legacy', sa.Boolean(), nullable=False),
    sa.Column('row_order', sa.Integer(), nullable=True),
    sa.Column('consignor_exporter', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('import_file_number', sa.String(length=64), nullable=True),
    sa.Column('import_entry_date', sa.Date(), nullable=True),
    sa.Column('import_entry_number', sa.String(length=64), nullable=True),
    sa.Column('hs_code', sa.String(length=32), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('supplementary_units', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('unit', sa.String(length=16), nullable=True),
    sa.Column('quantity_imported', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('customs_value_kes', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('bif_value_kes', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('balance_quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('balance_customs_value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('balance_bif_value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('balance_supplementary_units', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_lines_hs_code'), 'import_lines', ['hs_code'], unique=False)
    op.create_index(op.f('ix_import_lines_import_entry_number'), 'import_lines', ['import_entry_number'], unique=False)
    op.create_table('export_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_line_id', sa.Integer(), nullable=False),
    sa.Column('source_document_id', sa.Integer(), nullable=True),
    sa.Column('is_legacy', sa.Boolean(), nullable=False),
    sa.Column('row_order', sa.Integer(), nullable=True),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('export_file_number', sa.String(length=64), nullable=True),
    sa.Column('export_entry_date', sa.Date(), nullable=True),
    sa.Column('export_entry_number', sa.String(length=64), nullable=True),
    sa.Column('ppb_permit', sa.String(length=64), nullable=True),
    sa.Column('supplementary_units_exported', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('unit', sa.String(length=16), nullable=True),
    sa.Column('quantity_exported', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('customs_value_exported', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('bif_value_exported', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['import_line_id'], ['import_lines.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_export_lines_export_entry_number'), 'export_lines', ['export_entry_number'], unique=False)
    op.create_index(op.f('ix_export_lines_import_line_id'), 'export_lines', ['import_line_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_export_lines_import_line_id'), table_name='export_lines')
    op.drop_index(op.f('ix_export_lines_export_entry_number'), table_name='export_lines')
    op.drop_table('export_lines')
    op.drop_index(op.f('ix_import_lines_import_entry_number'), table_name='import_lines')
    op.drop_index(op.f('ix_import_lines_hs_code'), table_name='import_lines')
    op.drop_table('import_lines')
    op.drop_index(op.f('ix_source_documents_file_hash'), table_name='source_documents')
    op.drop_table('source_documents')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('allowed_units')
    op.drop_table('allowed_countries')
    # ### end Alembic commands ###
